### ISSUE TITLE
session saves

### ISSUE THREAD

**Issue by briceburg** [manuel-colmenero/vim-simple-session#1]
Hey -- thanks for this plugin! I wanted to make sure session state was saved whenever new buffers are opened, so poked around. Found:

``` vim
augroup SimpleSession
  autocmd BufEnter,VimLeave * call session#save()
augroup END
```

so it appears to be the case, although all the documentation and even code comments state that sessions are "saved on close". Are they also saved on new buffers? 

Thanks!

**Comment by manuel-colmenero** [comment]
Hi, thanks for the kind words! I'm glad you find this useful.

> Are they also saved on new buffers?

Yes, whenever a new buffer is created, the session is stored. It was a feature added afterwards, and the documentation is not up to date. I'll fix that to avoid confusion.

Thanks for the heads up!

**Comment by manuel-colmenero** [comment]
Fixed.
